Traceback (most recent call last):
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/SLI39/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
lat = rsl_subset.isel(record_id=rid).lat
lon = rsl_subset.isel(record_id=rid).lon
sla_detrended.sel(latitude=lat, longitude=lon, method='nearest').plot(label='Sea Level Anomaly (m)')
sla_detrended_area_weighted.sel(latitude=lat, longitude=lon, method='nearest').plot(label='Area Weighted Sea Level Anomaly (m)')

# change the title to station name
plt.title(rsl_subset['station_name'].isel(record_id=rid).values)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m lat [38;5;241m=[39m rsl_subset[38;5;241m.[39misel(record_id[38;5;241m=[39m[43mrid[49m)[38;5;241m.[39mlat
[1;32m      2[0m lon [38;5;241m=[39m rsl_subset[38;5;241m.[39misel(record_id[38;5;241m=[39mrid)[38;5;241m.[39mlon
[1;32m      3[0m sla_detrended[38;5;241m.[39msel(latitude[38;5;241m=[39mlat, longitude[38;5;241m=[39mlon, method[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnearest[39m[38;5;124m'[39m)[38;5;241m.[39mplot(label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mSea Level Anomaly (m)[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'rid' is not defined

